default_install_hook_types:
    - pre-commit
    - commit-msg
default_stages:
    - pre-commit

repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.1.0
      hooks:
          - id: prettier
            language: node
            additional_dependencies:
                - '@trivago/prettier-plugin-sort-imports@^6.0.0'
                - prettier@^3.7.4
                - prettier-plugin-sort-json@^4.1.1

    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v9.39.1
      hooks:
          - id: eslint
            language: node
            types: [file]
            types_or: [javascript, jsx, ts, tsx]
            additional_dependencies:
                - eslint@^9.39.2
                - eslint-import-resolver-typescript@^4.4.4
                - eslint-plugin-import@^2.32.0
                - typescript-eslint@^8.50.0

    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v9.24.0
      hooks:
          - id: commitlint
            stages: [commit-msg]
            language: node
            additional_dependencies:
                - '@commitlint/cli@^20.2.0'
                - '@commitlint/config-conventional@^20.2.0'
